-- 1. BASE TABLES
CREATE TABLE IF NOT EXISTS Seasons (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT NOT NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Opponents (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT NOT NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS SeasonOpponents (
    SeasonId BIGINT NOT NULL REFERENCES Seasons(Id),
    OpponentId BIGINT NOT NULL REFERENCES Opponents(Id),
    PRIMARY KEY (SeasonId, OpponentId)
);

CREATE TABLE IF NOT EXISTS Players (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT NOT NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS SeasonPlayers (
    SeasonId BIGINT NOT NULL REFERENCES Seasons(Id),
    PlayerId BIGINT NOT NULL REFERENCES Players(Id),
    PRIMARY KEY (SeasonId, PlayerId)
);

CREATE TABLE IF NOT EXISTS Games (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    SeasonId BIGINT NOT NULL REFERENCES Seasons(Id),
    GameNumber INT NOT NULL DEFAULT 0,
    Date TIMESTAMP WITH TIME ZONE NOT NULL,
    Diamond TEXT NOT NULL DEFAULT '',
    OpponentId BIGINT NOT NULL REFERENCES Opponents(Id),
    Type INT NOT NULL DEFAULT 0,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Stats (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    PlayerId BIGINT NOT NULL REFERENCES Players(Id),
    GameId BIGINT NOT NULL REFERENCES Games(Id),
    BO INT NOT NULL DEFAULT 0,
    H1B INT NOT NULL DEFAULT 0,
    H2B INT NOT NULL DEFAULT 0,
    H3B INT NOT NULL DEFAULT 0,
    H4B INT NOT NULL DEFAULT 0,
    HR INT NOT NULL DEFAULT 0,
    FC INT NOT NULL DEFAULT 0,
    BB INT NOT NULL DEFAULT 0,
    SF INT NOT NULL DEFAULT 0,
    K INT NOT NULL DEFAULT 0,
    KF INT NOT NULL DEFAULT 0,
    GO INT NOT NULL DEFAULT 0,
    FO INT NOT NULL DEFAULT 0,
    R INT NOT NULL DEFAULT 0,
    RBI INT NOT NULL DEFAULT 0
);

-- 2. AUTH & LOGGING TABLES
CREATE TABLE IF NOT EXISTS Permissions (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS UserRoles (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT NOT NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS RolePermissions (
    RoleId BIGINT NOT NULL REFERENCES UserRoles(Id),
    PermissionId BIGINT NOT NULL REFERENCES Permissions(Id),
    PRIMARY KEY (RoleId, PermissionId)
);

CREATE TABLE IF NOT EXISTS Users (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Email TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS UserUserRoles (
    UserId BIGINT NOT NULL REFERENCES Users(Id),
    RoleId BIGINT NOT NULL REFERENCES UserRoles(Id),
    PRIMARY KEY (UserId, RoleId)
);

CREATE TABLE IF NOT EXISTS UserLogs (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    UserId BIGINT REFERENCES Users(Id),
    UserEmail TEXT NOT NULL,
    Action INT NOT NULL, -- 0: Created, 1: Updated, 2: Deleted
    EntityType TEXT NOT NULL,
    EntityId TEXT NOT NULL,
    Description TEXT NOT NULL,
    Timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. INDEXES
CREATE UNIQUE INDEX IF NOT EXISTS idx_seasons_name_active ON Seasons(Name) WHERE IsDeleted = FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS idx_opponents_name_active ON Opponents(Name) WHERE IsDeleted = FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS idx_players_name_active ON Players(Name) WHERE IsDeleted = FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS idx_userroles_name_active ON UserRoles(Name) WHERE IsDeleted = FALSE;

-- 4. SEED DATA
INSERT INTO Permissions (Name) VALUES 
('Manage Games'), ('Manage Players'), ('Manage Opponents'), 
('Manage Seasons'), ('Manage Users'), ('Manage Roles'), ('Manage Logs')
ON CONFLICT (Name) DO NOTHING;

DO $$
DECLARE
    admin_role_id BIGINT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM UserRoles WHERE Name = 'Administrator') THEN
        INSERT INTO UserRoles (Name) VALUES ('Administrator') RETURNING Id INTO admin_role_id;
        INSERT INTO RolePermissions (RoleId, PermissionId)
        SELECT admin_role_id, Id FROM Permissions;
    END IF;
END $$;
