name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish application
        run: dotnet publish IsotopesStats/IsotopesStats.csproj -c Release -o release

      - name: Change base-tag in index.html for GitHub Pages
        # This replaces <base href="/" /> with <base href="/IsotopesStats/" />
        run: sed -i 's/<base href="\/" \/>/<base href="\/IsotopesStats\/" \/>/g' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
